// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Recipes_Data.Context;

#nullable disable

namespace Online_Recipes_Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240520200455_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("CategoryRecipe");

                    b.HasData(
                        new
                        {
                            RecipesId = 1,
                            CategoriesId = 1
                        },
                        new
                        {
                            RecipesId = 2,
                            CategoriesId = 1
                        },
                        new
                        {
                            RecipesId = 3,
                            CategoriesId = 1
                        },
                        new
                        {
                            RecipesId = 4,
                            CategoriesId = 2
                        },
                        new
                        {
                            RecipesId = 5,
                            CategoriesId = 2
                        },
                        new
                        {
                            RecipesId = 6,
                            CategoriesId = 2
                        },
                        new
                        {
                            RecipesId = 7,
                            CategoriesId = 3
                        },
                        new
                        {
                            RecipesId = 8,
                            CategoriesId = 3
                        },
                        new
                        {
                            RecipesId = 9,
                            CategoriesId = 3
                        });
                });

            modelBuilder.Entity("CommentRecipe", b =>
                {
                    b.Property<int>("CommentsId")
                        .HasColumnType("int");

                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.HasKey("CommentsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("CommentRecipe");
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("IngredientRecipe");

                    b.HasData(
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 1
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 2
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 3
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 4
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 5
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 6
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 7
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 8
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 9
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 10
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 11
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 12
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 13
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 14
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 15
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 16
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 17
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 18
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 19
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 20
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 21
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 22
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 23
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 24
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 25
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 7
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 26
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 27
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 28
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 29
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 15
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 30
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 31
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 32
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 33
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 27
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 15
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 34
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 35
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 26
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 7
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 6
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 36
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 22
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 3
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 37
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 38
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 39
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 21
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 40
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 30
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 7
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 26
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 3
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 41
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 42
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 6
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 43
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 15
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 44
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 26
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 30
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 45
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 4
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 38
                        },
                        new
                        {
                            RecipesId = 7,
                            IngredientsId = 46
                        },
                        new
                        {
                            RecipesId = 7,
                            IngredientsId = 47
                        },
                        new
                        {
                            RecipesId = 7,
                            IngredientsId = 6
                        },
                        new
                        {
                            RecipesId = 7,
                            IngredientsId = 48
                        },
                        new
                        {
                            RecipesId = 7,
                            IngredientsId = 49
                        },
                        new
                        {
                            RecipesId = 7,
                            IngredientsId = 50
                        },
                        new
                        {
                            RecipesId = 7,
                            IngredientsId = 51
                        },
                        new
                        {
                            RecipesId = 7,
                            IngredientsId = 13
                        },
                        new
                        {
                            RecipesId = 7,
                            IngredientsId = 44
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 52
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 53
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 54
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 13
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 26
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 15
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 7
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 6
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 35
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 28
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 51
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 55
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 56
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 27
                        },
                        new
                        {
                            RecipesId = 8,
                            IngredientsId = 39
                        },
                        new
                        {
                            RecipesId = 9,
                            IngredientsId = 57
                        },
                        new
                        {
                            RecipesId = 9,
                            IngredientsId = 27
                        },
                        new
                        {
                            RecipesId = 9,
                            IngredientsId = 26
                        },
                        new
                        {
                            RecipesId = 9,
                            IngredientsId = 30
                        },
                        new
                        {
                            RecipesId = 9,
                            IngredientsId = 35
                        },
                        new
                        {
                            RecipesId = 9,
                            IngredientsId = 15
                        },
                        new
                        {
                            RecipesId = 9,
                            IngredientsId = 44
                        },
                        new
                        {
                            RecipesId = 9,
                            IngredientsId = 38
                        },
                        new
                        {
                            RecipesId = 9,
                            IngredientsId = 41
                        });
                });

            modelBuilder.Entity("Ingredient_QuantityRecipe", b =>
                {
                    b.Property<int>("Ingredient_QuantitiesId")
                        .HasColumnType("int");

                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.HasKey("Ingredient_QuantitiesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("Ingredient_QuantityRecipe");
                });

            modelBuilder.Entity("Ingredient_QuantityRecipeIngredient", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("Ingredient_QuantitiesId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "Ingredient_QuantitiesId");

                    b.HasIndex("Ingredient_QuantitiesId");

                    b.ToTable("Ingredient_QuantityRecipeIngredient");

                    b.HasData(
                        new
                        {
                            IngredientsId = 1,
                            Ingredient_QuantitiesId = 19
                        },
                        new
                        {
                            IngredientsId = 2,
                            Ingredient_QuantitiesId = 5
                        },
                        new
                        {
                            IngredientsId = 3,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 4,
                            Ingredient_QuantitiesId = 5
                        },
                        new
                        {
                            IngredientsId = 5,
                            Ingredient_QuantitiesId = 20
                        },
                        new
                        {
                            IngredientsId = 6,
                            Ingredient_QuantitiesId = 5
                        },
                        new
                        {
                            IngredientsId = 7,
                            Ingredient_QuantitiesId = 7
                        },
                        new
                        {
                            IngredientsId = 8,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 9,
                            Ingredient_QuantitiesId = 16
                        },
                        new
                        {
                            IngredientsId = 10,
                            Ingredient_QuantitiesId = 16
                        },
                        new
                        {
                            IngredientsId = 11,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 12,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 13,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 14,
                            Ingredient_QuantitiesId = 18
                        },
                        new
                        {
                            IngredientsId = 15,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 16,
                            Ingredient_QuantitiesId = 18
                        },
                        new
                        {
                            IngredientsId = 17,
                            Ingredient_QuantitiesId = 12
                        },
                        new
                        {
                            IngredientsId = 18,
                            Ingredient_QuantitiesId = 12
                        },
                        new
                        {
                            IngredientsId = 19,
                            Ingredient_QuantitiesId = 18
                        },
                        new
                        {
                            IngredientsId = 20,
                            Ingredient_QuantitiesId = 17
                        },
                        new
                        {
                            IngredientsId = 21,
                            Ingredient_QuantitiesId = 18
                        },
                        new
                        {
                            IngredientsId = 22,
                            Ingredient_QuantitiesId = 14
                        },
                        new
                        {
                            IngredientsId = 23,
                            Ingredient_QuantitiesId = 3
                        },
                        new
                        {
                            IngredientsId = 24,
                            Ingredient_QuantitiesId = 18
                        },
                        new
                        {
                            IngredientsId = 25,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 26,
                            Ingredient_QuantitiesId = 6
                        },
                        new
                        {
                            IngredientsId = 27,
                            Ingredient_QuantitiesId = 13
                        },
                        new
                        {
                            IngredientsId = 28,
                            Ingredient_QuantitiesId = 12
                        },
                        new
                        {
                            IngredientsId = 29,
                            Ingredient_QuantitiesId = 10
                        },
                        new
                        {
                            IngredientsId = 30,
                            Ingredient_QuantitiesId = 15
                        },
                        new
                        {
                            IngredientsId = 31,
                            Ingredient_QuantitiesId = 6
                        },
                        new
                        {
                            IngredientsId = 32,
                            Ingredient_QuantitiesId = 3
                        },
                        new
                        {
                            IngredientsId = 33,
                            Ingredient_QuantitiesId = 21
                        },
                        new
                        {
                            IngredientsId = 34,
                            Ingredient_QuantitiesId = 18
                        },
                        new
                        {
                            IngredientsId = 35,
                            Ingredient_QuantitiesId = 12
                        },
                        new
                        {
                            IngredientsId = 36,
                            Ingredient_QuantitiesId = 8
                        },
                        new
                        {
                            IngredientsId = 37,
                            Ingredient_QuantitiesId = 14
                        },
                        new
                        {
                            IngredientsId = 38,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 39,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 40,
                            Ingredient_QuantitiesId = 5
                        },
                        new
                        {
                            IngredientsId = 41,
                            Ingredient_QuantitiesId = 22
                        },
                        new
                        {
                            IngredientsId = 42,
                            Ingredient_QuantitiesId = 23
                        },
                        new
                        {
                            IngredientsId = 43,
                            Ingredient_QuantitiesId = 18
                        },
                        new
                        {
                            IngredientsId = 44,
                            Ingredient_QuantitiesId = 1
                        },
                        new
                        {
                            IngredientsId = 45,
                            Ingredient_QuantitiesId = 8
                        },
                        new
                        {
                            IngredientsId = 46,
                            Ingredient_QuantitiesId = 16
                        },
                        new
                        {
                            IngredientsId = 47,
                            Ingredient_QuantitiesId = 14
                        },
                        new
                        {
                            IngredientsId = 48,
                            Ingredient_QuantitiesId = 7
                        },
                        new
                        {
                            IngredientsId = 49,
                            Ingredient_QuantitiesId = 16
                        },
                        new
                        {
                            IngredientsId = 50,
                            Ingredient_QuantitiesId = 3
                        },
                        new
                        {
                            IngredientsId = 51,
                            Ingredient_QuantitiesId = 14
                        },
                        new
                        {
                            IngredientsId = 52,
                            Ingredient_QuantitiesId = 21
                        },
                        new
                        {
                            IngredientsId = 53,
                            Ingredient_QuantitiesId = 19
                        },
                        new
                        {
                            IngredientsId = 54,
                            Ingredient_QuantitiesId = 12
                        },
                        new
                        {
                            IngredientsId = 55,
                            Ingredient_QuantitiesId = 24
                        },
                        new
                        {
                            IngredientsId = 56,
                            Ingredient_QuantitiesId = 14
                        },
                        new
                        {
                            IngredientsId = 57,
                            Ingredient_QuantitiesId = 12
                        });
                });

            modelBuilder.Entity("Online_Recipes_Domain.Account.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Online_Recipes_Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vegetarian"
                        });
                });

            modelBuilder.Entity("Online_Recipes_Domain.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UsersComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Online_Recipes_Domain.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Product")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Product = "Pork"
                        },
                        new
                        {
                            Id = 2,
                            Product = "Pepper paste"
                        },
                        new
                        {
                            Id = 3,
                            Product = "Blonde"
                        },
                        new
                        {
                            Id = 4,
                            Product = "Orange"
                        },
                        new
                        {
                            Id = 5,
                            Product = "Brunette"
                        },
                        new
                        {
                            Id = 6,
                            Product = "onion"
                        },
                        new
                        {
                            Id = 7,
                            Product = "Olive oil"
                        },
                        new
                        {
                            Id = 8,
                            Product = "Shall"
                        },
                        new
                        {
                            Id = 9,
                            Product = "Curget"
                        },
                        new
                        {
                            Id = 10,
                            Product = "Mushroom"
                        },
                        new
                        {
                            Id = 11,
                            Product = "back pepper"
                        },
                        new
                        {
                            Id = 12,
                            Product = "Sweet chili"
                        },
                        new
                        {
                            Id = 13,
                            Product = "Dried thyme"
                        },
                        new
                        {
                            Id = 14,
                            Product = "chickpea"
                        },
                        new
                        {
                            Id = 15,
                            Product = "salt"
                        },
                        new
                        {
                            Id = 16,
                            Product = "veal"
                        },
                        new
                        {
                            Id = 17,
                            Product = "bacon"
                        },
                        new
                        {
                            Id = 18,
                            Product = "meat sausage"
                        },
                        new
                        {
                            Id = 19,
                            Product = "spare ribs"
                        },
                        new
                        {
                            Id = 20,
                            Product = "chicken"
                        },
                        new
                        {
                            Id = 21,
                            Product = "potato"
                        },
                        new
                        {
                            Id = 22,
                            Product = "carrot"
                        },
                        new
                        {
                            Id = 23,
                            Product = "savoy cabbage"
                        },
                        new
                        {
                            Id = 24,
                            Product = "scratched pasta"
                        },
                        new
                        {
                            Id = 25,
                            Product = "cumin"
                        },
                        new
                        {
                            Id = 26,
                            Product = "garlic"
                        },
                        new
                        {
                            Id = 27,
                            Product = "water"
                        },
                        new
                        {
                            Id = 28,
                            Product = "yellow corn flour"
                        },
                        new
                        {
                            Id = 29,
                            Product = "green soup"
                        },
                        new
                        {
                            Id = 30,
                            Product = "oil"
                        },
                        new
                        {
                            Id = 31,
                            Product = "green laurel sticks"
                        },
                        new
                        {
                            Id = 32,
                            Product = "fillet meat in cubes"
                        },
                        new
                        {
                            Id = 33,
                            Product = "ling"
                        },
                        new
                        {
                            Id = 34,
                            Product = "shrimp"
                        },
                        new
                        {
                            Id = 35,
                            Product = "tomato"
                        },
                        new
                        {
                            Id = 36,
                            Product = "leek"
                        },
                        new
                        {
                            Id = 37,
                            Product = "noodle dough"
                        },
                        new
                        {
                            Id = 38,
                            Product = "coriander"
                        },
                        new
                        {
                            Id = 39,
                            Product = "parsley"
                        },
                        new
                        {
                            Id = 40,
                            Product = "cod fish"
                        },
                        new
                        {
                            Id = 41,
                            Product = "eggs"
                        },
                        new
                        {
                            Id = 42,
                            Product = "black olive"
                        },
                        new
                        {
                            Id = 43,
                            Product = "sea bream"
                        },
                        new
                        {
                            Id = 44,
                            Product = "pepper"
                        },
                        new
                        {
                            Id = 45,
                            Product = "fennel"
                        },
                        new
                        {
                            Id = 46,
                            Product = "pear"
                        },
                        new
                        {
                            Id = 47,
                            Product = "butter"
                        },
                        new
                        {
                            Id = 48,
                            Product = "white wine"
                        },
                        new
                        {
                            Id = 49,
                            Product = "risotto rice"
                        },
                        new
                        {
                            Id = 50,
                            Product = "broth"
                        },
                        new
                        {
                            Id = 51,
                            Product = "cheese"
                        },
                        new
                        {
                            Id = 52,
                            Product = "portobello mushroom"
                        },
                        new
                        {
                            Id = 53,
                            Product = "pumpkin"
                        },
                        new
                        {
                            Id = 54,
                            Product = "asparagus"
                        },
                        new
                        {
                            Id = 55,
                            Product = "almond"
                        },
                        new
                        {
                            Id = 56,
                            Product = "rice"
                        },
                        new
                        {
                            Id = 57,
                            Product = "bread"
                        });
                });

            modelBuilder.Entity("Online_Recipes_Domain.Models.Ingredient_Quantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Measure")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ingredient_Quantity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Measure = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Measure = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            Measure = 0,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            Measure = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            Measure = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            Measure = 3,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 7,
                            Measure = 2,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 8,
                            Measure = 1,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 9,
                            Measure = 2,
                            Quantity = 150
                        },
                        new
                        {
                            Id = 10,
                            Measure = 1,
                            Quantity = 150
                        },
                        new
                        {
                            Id = 11,
                            Measure = 2,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 12,
                            Measure = 1,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 13,
                            Measure = 2,
                            Quantity = 250
                        },
                        new
                        {
                            Id = 14,
                            Measure = 1,
                            Quantity = 250
                        },
                        new
                        {
                            Id = 15,
                            Measure = 2,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 16,
                            Measure = 1,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 17,
                            Measure = 1,
                            Quantity = 400
                        },
                        new
                        {
                            Id = 18,
                            Measure = 1,
                            Quantity = 500
                        },
                        new
                        {
                            Id = 19,
                            Measure = 1,
                            Quantity = 600
                        },
                        new
                        {
                            Id = 20,
                            Measure = 1,
                            Quantity = 800
                        },
                        new
                        {
                            Id = 21,
                            Measure = 1,
                            Quantity = 700
                        },
                        new
                        {
                            Id = 22,
                            Measure = 4,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 23,
                            Measure = 3,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 24,
                            Measure = 1,
                            Quantity = 40
                        });
                });

            modelBuilder.Entity("Online_Recipes_Domain.Models.Preparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Preparation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Steps = "Massage the meat with the pepper paste, add the bay leaf broken into pieces and drizzle with the juice of an orange."
                        },
                        new
                        {
                            Id = 2,
                            Steps = "Cut the other orange into thick slices and then into pieces and mix it with the meat. Let marinate for at least 1 hour."
                        },
                        new
                        {
                            Id = 3,
                            Steps = "Peel the chestnuts and set aside. Also peel the onions and cut them into half moons."
                        },
                        new
                        {
                            Id = 4,
                            Steps = "Place the meat and marinade in a pan, add half the onion and olive oil. Mix well and cook, covered and over low heat, for around 50 minutes or until the meat is tender."
                        },
                        new
                        {
                            Id = 5,
                            Steps = "Brown the remaining onion in a large frying pan with the remaining olive oil. Add the chestnuts and season with salt."
                        },
                        new
                        {
                            Id = 6,
                            Steps = "Cut the courgette into sticks and the mushrooms in half and add them to the chestnuts. Sprinkle with a pinch of pepper, paprika and thyme."
                        },
                        new
                        {
                            Id = 7,
                            Steps = "Cover the pan and let it cook gently for about 30 minutes. If necessary, spray with a little water. Mix with the meat and serve."
                        },
                        new
                        {
                            Id = 8,
                            Steps = "The day before, soak the grain in water."
                        },
                        new
                        {
                            Id = 9,
                            Steps = "Before preparing, drain the grain and place it in a pan with plenty of water, seasoned with half the salt, along with the veal."
                        },
                        new
                        {
                            Id = 10,
                            Steps = "When the grain starts to cook, add the bacon, chorizo, spare ribs and chicken and let it cook for around 1 hour."
                        },
                        new
                        {
                            Id = 11,
                            Steps = "Remove the meat as soon as it is cooked. Add the peeled and diced potatoes, as well as the sliced ​​carrots and striped cabbage. Add water so that the vegetables are covered."
                        },
                        new
                        {
                            Id = 12,
                            Steps = "After 10 minutes, add the dough, season with the remaining salt and, if necessary, add a little more water."
                        },
                        new
                        {
                            Id = 13,
                            Steps = "Cut the meat into pieces and return to the pan. Let it heat up and, before serving, sprinkle with cumin."
                        },
                        new
                        {
                            Id = 14,
                            Steps = "Pour the olive oil and finely grated or chopped garlic into a pan. Let it cook for a minute. Add the water and bring to a boil."
                        },
                        new
                        {
                            Id = 15,
                            Steps = "Dissolve the flour in a little cold water and, when the water in the pan is boiling, add the flour and stir very well to make corn porridge."
                        },
                        new
                        {
                            Id = 16,
                            Steps = "At the same time, add the cabbage. Season with salt and mix everything."
                        },
                        new
                        {
                            Id = 17,
                            Steps = "Keep stirring to avoid lumps and let the flour cook over medium heat for about 5 minutes, being careful not to let it stick to the pan."
                        },
                        new
                        {
                            Id = 18,
                            Steps = "When the dough has a solid consistency, turn off the heat, place it on a tray and let it cool. Place in the fridge to solidify, at least 3 hours."
                        },
                        new
                        {
                            Id = 19,
                            Steps = "When the dough is cooked, heat the oil, cut the dough into sticks and fry until golden brown."
                        },
                        new
                        {
                            Id = 20,
                            Steps = "Using a sharp knife, sharpen the ends of the bay leaves to create skewers."
                        },
                        new
                        {
                            Id = 21,
                            Steps = "Thread the pieces of meat onto the skewers."
                        },
                        new
                        {
                            Id = 22,
                            Steps = "Season the meat with salt and grill, turning it regularly. When cooked to taste, serve with fried corn sticks."
                        },
                        new
                        {
                            Id = 23,
                            Steps = "In a pan, place the fish and cover with about a liter and a half of water. Add the salt and bring to the boil. Let it boil for 10 minutes and remove the fish with a slotted spoon. Add the shrimp shells and heads to the fish cooking broth and bring to a boil."
                        },
                        new
                        {
                            Id = 24,
                            Steps = "Peel and chop the garlic cloves, peel the carrots and cut them into slices."
                        },
                        new
                        {
                            Id = 25,
                            Steps = "In a pan, with the olive oil, sauté the chopped garlic cloves and, when they start to brown, the leek and chopped onion. Let cook until the vegetables are soft. Add the carrot slices, tomato and bay leaf. Cover and cook over low heat until the tomato is soft."
                        },
                        new
                        {
                            Id = 26,
                            Steps = "Grind the shrimp shells and heads with a hand blender and strain the broth using a mesh strainer. Pour the broth over the stew and when it boils, add the pasta. Cover and let cook until al dente."
                        },
                        new
                        {
                            Id = 27,
                            Steps = "Clean the fish of skin and bones and break it into large pieces. Add the fish and coriander to the pasta and serve immediately."
                        },
                        new
                        {
                            Id = 28,
                            Steps = "Peel the potatoes and cut them into very thin sticks to obtain straw potatoes. Soak them in water for about half an hour to remove excess gum."
                        },
                        new
                        {
                            Id = 29,
                            Steps = "Meanwhile, remove the skin and bones from the cod and shred it with your hands."
                        },
                        new
                        {
                            Id = 30,
                            Steps = "Drain the potatoes and dry them well with a towel or kitchen paper. Fry them in the previously heated oil."
                        },
                        new
                        {
                            Id = 31,
                            Steps = "Meanwhile, heat the oil in a frying pan and sauté the sliced ​​onion, peeled and cut into half moons, the garlic, peeled and chopped, and the bay leaf."
                        },
                        new
                        {
                            Id = 32,
                            Steps = "When the onion and garlic start to soften, add the shredded cod and cover the pan."
                        },
                        new
                        {
                            Id = 33,
                            Steps = "Cook over low heat until the cod turns white."
                        },
                        new
                        {
                            Id = 34,
                            Steps = "Remove the bay leaf from the mixture and add the fries."
                        },
                        new
                        {
                            Id = 35,
                            Steps = "Add the eggs, previously beaten, stir them gently, allowing them to coat all the ingredients. Don't let the eggs cook and dry out too much."
                        },
                        new
                        {
                            Id = 36,
                            Steps = "Before serving, sprinkle with chopped parsley and decorate with olives."
                        },
                        new
                        {
                            Id = 37,
                            Steps = "Season the fillets with half the salt, pepper and chopped garlic."
                        },
                        new
                        {
                            Id = 38,
                            Steps = "Heat half the olive oil in a non-stick frying pan and when it is hot, add the fillets and cook for 2 minutes on each side. Remove and reserve."
                        },
                        new
                        {
                            Id = 39,
                            Steps = "Add the remaining olive oil, add the fennel and the juice and zest of an orange. Scrape the bottom with a wooden spoon."
                        },
                        new
                        {
                            Id = 40,
                            Steps = "Add the segments of the other orange, the remaining salt and pepper."
                        },
                        new
                        {
                            Id = 41,
                            Steps = "Return the fillets to the pan and cook for another 3 minutes."
                        },
                        new
                        {
                            Id = 42,
                            Steps = "Cut a pear with the skin into thin slices. Heat two tablespoons of butter in a frying pan and sauté the pear slices until golden or slightly caramelized. Reserve."
                        },
                        new
                        {
                            Id = 43,
                            Steps = "Cut the remaining pears into small cubes, also with the skin on. Reserve."
                        },
                        new
                        {
                            Id = 44,
                            Steps = "In a high frying pan, heat two tablespoons of butter, add the chopped onion and cook for 2 minutes. Add the rice and mix. Add the glass of wine and let it absorb."
                        },
                        new
                        {
                            Id = 45,
                            Steps = "Then, add ladlefuls of broth (vegetable broth diluted in 1.5L of water), let it absorb completely until adding more broth again and stir constantly. Do this process for around 15 minutes."
                        },
                        new
                        {
                            Id = 46,
                            Steps = "After 15 minutes, add the pear cubes and continue to stir."
                        },
                        new
                        {
                            Id = 47,
                            Steps = "When the rice is cooked, add half of the Azeitão cheese paste, the remaining butter and mix."
                        },
                        new
                        {
                            Id = 48,
                            Steps = "Distribute between four plates and place the remaining cheese paste and sautéed pear slices on top."
                        },
                        new
                        {
                            Id = 49,
                            Steps = "Finish with thyme and pepper."
                        },
                        new
                        {
                            Id = 50,
                            Steps = "Preheat the oven to 180ºC. Clean the mushrooms with kitchen paper, remove the stems and, using a spoon, carefully excavate part of the pulp, without tearing the caps. Reserve the feet and pulp."
                        },
                        new
                        {
                            Id = 51,
                            Steps = "Place the mushroom caps on a baking tray lined with baking paper and place ⅔ of the pumpkin in slices about 5 mm thick next to them."
                        },
                        new
                        {
                            Id = 52,
                            Steps = "Remove the fibrous base of the asparagus, cut off the spiked ends and add them to the tray. Reserve the rest."
                        },
                        new
                        {
                            Id = 53,
                            Steps = "Sprinkle with the thyme, half the minced garlic and ½ teaspoon of salt. Drizzle with a tablespoon of olive oil and place the tray in the oven for around 10 to 15 minutes."
                        },
                        new
                        {
                            Id = 54,
                            Steps = "For the filling, heat 1 ½ tablespoons of olive oil in a wide frying pan, add the onion and the remaining chopped garlic and let it brown. Add the mushroom stems and pulp and the finely chopped sun-dried tomato. Add the remaining asparagus cut into slices and the remaining diced pumpkin."
                        },
                        new
                        {
                            Id = 55,
                            Steps = "Season with ½ teaspoon of salt and sauté over medium to high heat, stirring frequently for about 5 minutes."
                        },
                        new
                        {
                            Id = 56,
                            Steps = "Add the crumbled cornbread crumbs and cook for another 2 to 3 minutes."
                        },
                        new
                        {
                            Id = 57,
                            Steps = "When cooked, remove the mushroom caps from the oven and divide the filling between them, distributing the cheese and almonds on top. Place back in the oven for another 10 to 15 minutes."
                        },
                        new
                        {
                            Id = 58,
                            Steps = "Meanwhile, heat the remaining oil in a pan, add the rice and fry for about 1 minute, stirring frequently."
                        },
                        new
                        {
                            Id = 59,
                            Steps = "Pour in boiling water, season with the remaining salt and cook covered for 15 minutes. When serving, sprinkle with chopped parsley."
                        },
                        new
                        {
                            Id = 60,
                            Steps = "Tear the bread into pieces into a bowl, cover them with hot water and let the bread absorb."
                        },
                        new
                        {
                            Id = 61,
                            Steps = "Crush the garlic cloves, with the skin, and brown them in the hot olive oil. Remove the skin from the garlic, add the tomato, cleaned of seeds and chopped into small cubes, and cook over low heat for about 5 minutes."
                        },
                        new
                        {
                            Id = 62,
                            Steps = "Squeeze the bread, if necessary to remove excess water, and add it to the tomato. Keep stirring constantly, over the heat, until the bread is at the desired consistency."
                        },
                        new
                        {
                            Id = 63,
                            Steps = "Mix the coriander into the mixture and place the bread in two bowls. Make some wells in the middle, add the egg yolks and mix quickly. Serve immediately."
                        });
                });

            modelBuilder.Entity("Online_Recipes_Domain.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Star = 4
                        },
                        new
                        {
                            Id = 2,
                            Star = 3
                        },
                        new
                        {
                            Id = 3,
                            Star = 5
                        });
                });

            modelBuilder.Entity("Online_Recipes_Domain.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("IsApproved")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTime = 90,
                            CreateDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1159),
                            Description = "Discover the authenticity of our pork Rojões with chestnuts. Enjoy irresistible flavors and gastronomic tradition, inspired by the richness of the Portuguese Mediterranean Diet!",
                            Difficulty = 0,
                            IsApproved = "true",
                            ModifiedDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1211),
                            Name = "Pork rojões with chestnutts",
                            Photo = "/assets/Pork rojões with chestnuts.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CookingTime = 30,
                            CreateDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1216),
                            Description = "In Viseu, to moralize the troops who were going through difficult times, instructions were given to reinforce their diet. From the barracks to the table, Viseu-style ranch was born, a dish that combines chickpeas, potatoes, vegetables, thick pasta and pork, veal and chicken.",
                            Difficulty = 1,
                            IsApproved = "true",
                            ModifiedDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1218),
                            Name = "Viseu`s Ranch",
                            Photo = "/assets/Viseu Ranch.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CookingTime = 60,
                            CreateDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1220),
                            Description = "Probably the best-known Madeiran dish outside the archipelago. Kebabs are usually accompanied with fried corn, a snack made with cooked corn flour, then cut into cubes and fried, which is almost as good as the kebab itself.",
                            Difficulty = 1,
                            IsApproved = "true",
                            ModifiedDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1221),
                            Name = "Madeiran kebabs with fried corn",
                            Photo = "/assets/Madeiran kebabs with fried corn.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CookingTime = 60,
                            CreateDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1224),
                            Description = "Fish pasta is a main course meal, but can be served as a starter for a lighter second course.",
                            Difficulty = 0,
                            IsApproved = "true",
                            ModifiedDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1225),
                            Name = "Fish pasta",
                            Photo = "/assets/Fish pasta.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CookingTime = 45,
                            CreateDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1227),
                            Description = "With cod, eggs and potatoes, this is one of the most popular recipes among the Portuguese. Easy and quick to make, you can easily adapt the method and try it with fish, shredded chicken or even leek.",
                            Difficulty = 1,
                            IsApproved = "true",
                            ModifiedDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1228),
                            Name = "Cod fish à Brás",
                            Photo = "/assets/Cod fish à Brás.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CookingTime = 20,
                            CreateDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1230),
                            Description = "Fruits such as orange, lemon or tangerine are popular in countless recipes. Prepare these sea bream fillets with orange sauce and make the most of the color and sweet flavor in a quick and healthy meal.",
                            Difficulty = 1,
                            IsApproved = "true",
                            ModifiedDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1231),
                            Name = "Sea bream fillets with orange sauce",
                            Photo = "/assets/Sea bream fillets with orange sauce.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CookingTime = 30,
                            CreateDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1233),
                            Description = "This risotto combines the traditional flavor of Azeitão cheese and the sweetness of pear, representing the gastronomic authenticity of Portugal, with Italian influences.",
                            Difficulty = 0,
                            IsApproved = "true",
                            ModifiedDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1234),
                            Name = "Azeitão Cheese and pear risotto",
                            Photo = "/assets/Azeitão Cheese and pear risotto.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CookingTime = 60,
                            CreateDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1236),
                            Description = "Try stuffed Portobello mushrooms for a balanced meal. Rich in nutrients and vegetable protein, they are ideal for vegetarian diets.",
                            Difficulty = 2,
                            IsApproved = "true",
                            ModifiedDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1238),
                            Name = "Stuffed Portobello Mushrooms",
                            Photo = "/assets/Stuffed Portobello Mushrooms.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CookingTime = 25,
                            CreateDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1240),
                            Description = "Use leftover carcasses (papos-secos) or mixed bread and prepare a delicious bread soup with coriander and egg. A typical Portuguese dish, vegetarian and without food waste.",
                            Difficulty = 0,
                            IsApproved = "true",
                            ModifiedDate = new DateTime(2024, 5, 20, 21, 4, 54, 624, DateTimeKind.Local).AddTicks(1241),
                            Name = "Açorda with coriander and egg",
                            Photo = "/assets/Açorda with coriander and egg.jpg"
                        });
                });

            modelBuilder.Entity("PreparationRecipe", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("PreparationsId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "PreparationsId");

                    b.HasIndex("PreparationsId");

                    b.ToTable("PreparationRecipe");

                    b.HasData(
                        new
                        {
                            RecipesId = 1,
                            PreparationsId = 1
                        },
                        new
                        {
                            RecipesId = 1,
                            PreparationsId = 2
                        },
                        new
                        {
                            RecipesId = 1,
                            PreparationsId = 3
                        },
                        new
                        {
                            RecipesId = 1,
                            PreparationsId = 4
                        },
                        new
                        {
                            RecipesId = 1,
                            PreparationsId = 5
                        },
                        new
                        {
                            RecipesId = 1,
                            PreparationsId = 6
                        },
                        new
                        {
                            RecipesId = 1,
                            PreparationsId = 7
                        },
                        new
                        {
                            RecipesId = 2,
                            PreparationsId = 8
                        },
                        new
                        {
                            RecipesId = 2,
                            PreparationsId = 9
                        },
                        new
                        {
                            RecipesId = 2,
                            PreparationsId = 10
                        },
                        new
                        {
                            RecipesId = 2,
                            PreparationsId = 11
                        },
                        new
                        {
                            RecipesId = 2,
                            PreparationsId = 12
                        },
                        new
                        {
                            RecipesId = 2,
                            PreparationsId = 13
                        },
                        new
                        {
                            RecipesId = 3,
                            PreparationsId = 14
                        },
                        new
                        {
                            RecipesId = 3,
                            PreparationsId = 15
                        },
                        new
                        {
                            RecipesId = 3,
                            PreparationsId = 16
                        },
                        new
                        {
                            RecipesId = 3,
                            PreparationsId = 17
                        },
                        new
                        {
                            RecipesId = 3,
                            PreparationsId = 18
                        },
                        new
                        {
                            RecipesId = 3,
                            PreparationsId = 19
                        },
                        new
                        {
                            RecipesId = 3,
                            PreparationsId = 20
                        },
                        new
                        {
                            RecipesId = 3,
                            PreparationsId = 21
                        },
                        new
                        {
                            RecipesId = 3,
                            PreparationsId = 22
                        },
                        new
                        {
                            RecipesId = 4,
                            PreparationsId = 23
                        },
                        new
                        {
                            RecipesId = 4,
                            PreparationsId = 24
                        },
                        new
                        {
                            RecipesId = 4,
                            PreparationsId = 25
                        },
                        new
                        {
                            RecipesId = 4,
                            PreparationsId = 26
                        },
                        new
                        {
                            RecipesId = 4,
                            PreparationsId = 27
                        },
                        new
                        {
                            RecipesId = 5,
                            PreparationsId = 28
                        },
                        new
                        {
                            RecipesId = 5,
                            PreparationsId = 29
                        },
                        new
                        {
                            RecipesId = 5,
                            PreparationsId = 30
                        },
                        new
                        {
                            RecipesId = 5,
                            PreparationsId = 31
                        },
                        new
                        {
                            RecipesId = 5,
                            PreparationsId = 32
                        },
                        new
                        {
                            RecipesId = 5,
                            PreparationsId = 33
                        },
                        new
                        {
                            RecipesId = 5,
                            PreparationsId = 34
                        },
                        new
                        {
                            RecipesId = 5,
                            PreparationsId = 35
                        },
                        new
                        {
                            RecipesId = 5,
                            PreparationsId = 36
                        },
                        new
                        {
                            RecipesId = 6,
                            PreparationsId = 37
                        },
                        new
                        {
                            RecipesId = 6,
                            PreparationsId = 38
                        },
                        new
                        {
                            RecipesId = 6,
                            PreparationsId = 39
                        },
                        new
                        {
                            RecipesId = 6,
                            PreparationsId = 40
                        },
                        new
                        {
                            RecipesId = 6,
                            PreparationsId = 41
                        },
                        new
                        {
                            RecipesId = 7,
                            PreparationsId = 42
                        },
                        new
                        {
                            RecipesId = 7,
                            PreparationsId = 43
                        },
                        new
                        {
                            RecipesId = 7,
                            PreparationsId = 44
                        },
                        new
                        {
                            RecipesId = 7,
                            PreparationsId = 45
                        },
                        new
                        {
                            RecipesId = 7,
                            PreparationsId = 46
                        },
                        new
                        {
                            RecipesId = 7,
                            PreparationsId = 47
                        },
                        new
                        {
                            RecipesId = 7,
                            PreparationsId = 48
                        },
                        new
                        {
                            RecipesId = 7,
                            PreparationsId = 49
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 50
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 51
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 52
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 53
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 54
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 55
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 56
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 57
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 58
                        },
                        new
                        {
                            RecipesId = 8,
                            PreparationsId = 59
                        },
                        new
                        {
                            RecipesId = 9,
                            PreparationsId = 60
                        },
                        new
                        {
                            RecipesId = 9,
                            PreparationsId = 61
                        },
                        new
                        {
                            RecipesId = 9,
                            PreparationsId = 62
                        },
                        new
                        {
                            RecipesId = 9,
                            PreparationsId = 63
                        });
                });

            modelBuilder.Entity("RatingRecipe", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("RatingsId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "RatingsId");

                    b.HasIndex("RatingsId");

                    b.ToTable("RatingRecipe");

                    b.HasData(
                        new
                        {
                            RecipesId = 1,
                            RatingsId = 1
                        },
                        new
                        {
                            RecipesId = 2,
                            RatingsId = 2
                        },
                        new
                        {
                            RecipesId = 3,
                            RatingsId = 3
                        },
                        new
                        {
                            RecipesId = 4,
                            RatingsId = 1
                        },
                        new
                        {
                            RecipesId = 5,
                            RatingsId = 2
                        },
                        new
                        {
                            RecipesId = 6,
                            RatingsId = 3
                        },
                        new
                        {
                            RecipesId = 7,
                            RatingsId = 1
                        },
                        new
                        {
                            RecipesId = 8,
                            RatingsId = 2
                        },
                        new
                        {
                            RecipesId = 9,
                            RatingsId = 3
                        });
                });

            modelBuilder.Entity("RecipeUser", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RecipeUser");
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("Online_Recipes_Domain.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Recipes_Domain.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommentRecipe", b =>
                {
                    b.HasOne("Online_Recipes_Domain.Models.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Recipes_Domain.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.HasOne("Online_Recipes_Domain.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Recipes_Domain.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingredient_QuantityRecipe", b =>
                {
                    b.HasOne("Online_Recipes_Domain.Models.Ingredient_Quantity", null)
                        .WithMany()
                        .HasForeignKey("Ingredient_QuantitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Recipes_Domain.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingredient_QuantityRecipeIngredient", b =>
                {
                    b.HasOne("Online_Recipes_Domain.Models.Ingredient_Quantity", null)
                        .WithMany()
                        .HasForeignKey("Ingredient_QuantitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Recipes_Domain.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PreparationRecipe", b =>
                {
                    b.HasOne("Online_Recipes_Domain.Models.Preparation", null)
                        .WithMany()
                        .HasForeignKey("PreparationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Recipes_Domain.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatingRecipe", b =>
                {
                    b.HasOne("Online_Recipes_Domain.Models.Rating", null)
                        .WithMany()
                        .HasForeignKey("RatingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Recipes_Domain.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeUser", b =>
                {
                    b.HasOne("Online_Recipes_Domain.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Recipes_Domain.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
